using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi.Models;
using System.Text.Json.Serialization;

var builder = WebApplication.CreateBuilder(args);

builder.Configuration.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);

builder.Services.AddControllers().AddJsonOptions(o => { o.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.IgnoreCycles; });
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c => c.SwaggerDoc("v1", new OpenApiInfo { Title = "Restaurant Service (SQL Server - Windows Auth)", Version = "v1" }));

var conn = builder.Configuration.GetConnectionString("DefaultConnection");
builder.Services.AddDbContext<AppDbContext>(options => options.UseSqlServer(conn));

var app = builder.Build();
app.UseSwagger();
app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "Restaurant Service v1"));
app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    try
    {
        db.Database.Migrate();
    }
    catch (Exception ex)
    {
        var logger = scope.ServiceProvider.GetRequiredService<ILogger<Program>>();
        logger.LogWarning(ex, "Could not apply migrations at startup. Ensure SQL Server is running and accessible via Windows Authentication.");
    }

    if (!db.Restaurants.Any())
    {
        db.Restaurants.Add(new Restaurant { Name = "Green Garden", Cuisine = "Mexican", City = "Pune", Rating = 4.8, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Spice Diner", Cuisine = "Chinese", City = "Chennai", Rating = 3.8, IsOpen = false });
        db.Restaurants.Add(new Restaurant { Name = "Golden Corner", Cuisine = "Thai", City = "Pune", Rating = 4.0, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Street Diner", Cuisine = "Mexican", City = "Bengaluru", Rating = 4.2, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Spice Plate", Cuisine = "Biryani", City = "Chennai", Rating = 3.6, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Coastal Hub", Cuisine = "Italian", City = "Kolkata", Rating = 4.0, IsOpen = false });
        db.Restaurants.Add(new Restaurant { Name = "Mama Table", Cuisine = "Italian", City = "Pune", Rating = 4.0, IsOpen = false });
        db.Restaurants.Add(new Restaurant { Name = "Street Table", Cuisine = "Chinese", City = "Bengaluru", Rating = 3.1, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Urban House", Cuisine = "South Indian", City = "Mumbai", Rating = 4.5, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Green Corner", Cuisine = "Continental", City = "Bengaluru", Rating = 4.3, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Fusion Treats", Cuisine = "Mexican", City = "Ahmedabad", Rating = 3.7, IsOpen = false });
        db.Restaurants.Add(new Restaurant { Name = "Street Diner", Cuisine = "Chinese", City = "Bengaluru", Rating = 3.9, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Fusion Bite", Cuisine = "Bakery", City = "Delhi", Rating = 4.3, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Spice Kitchen", Cuisine = "North Indian", City = "Hyderabad", Rating = 3.9, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Royal Hub", Cuisine = "Mexican", City = "Kolkata", Rating = 3.9, IsOpen = false });
        db.Restaurants.Add(new Restaurant { Name = "Fusion Garden", Cuisine = "South Indian", City = "Chennai", Rating = 3.3, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Street Hub", Cuisine = "North Indian", City = "Kolkata", Rating = 4.3, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Street Kitchen", Cuisine = "Cafe", City = "Delhi", Rating = 4.1, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Green Diner", Cuisine = "North Indian", City = "Mumbai", Rating = 4.1, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Green Bite", Cuisine = "Continental", City = "Kolkata", Rating = 3.2, IsOpen = false });
        db.Restaurants.Add(new Restaurant { Name = "Green Diner", Cuisine = "South Indian", City = "Bengaluru", Rating = 4.8, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Royal Diner", Cuisine = "Chinese", City = "Pune", Rating = 4.1, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Coastal Plate", Cuisine = "Italian", City = "Kolkata", Rating = 3.8, IsOpen = false });
        db.Restaurants.Add(new Restaurant { Name = "Street Hub", Cuisine = "North Indian", City = "Bengaluru", Rating = 5.0, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Royal Plate", Cuisine = "Continental", City = "Hyderabad", Rating = 4.0, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Mama Kitchen", Cuisine = "Mexican", City = "Delhi", Rating = 3.3, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Spice Kitchen", Cuisine = "South Indian", City = "Delhi", Rating = 3.8, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Spice Bite", Cuisine = "North Indian", City = "Delhi", Rating = 2.9, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Tasty Bite", Cuisine = "South Indian", City = "Pune", Rating = 4.5, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Fusion Kitchen", Cuisine = "Bakery", City = "Mumbai", Rating = 3.8, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Royal Kitchen", Cuisine = "North Indian", City = "Bengaluru", Rating = 3.6, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Green House", Cuisine = "South Indian", City = "Delhi", Rating = 4.5, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Royal Garden", Cuisine = "Biryani", City = "Pune", Rating = 3.2, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Spice Treats", Cuisine = "Continental", City = "Chennai", Rating = 4.3, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Coastal Treats", Cuisine = "Mexican", City = "Ahmedabad", Rating = 3.0, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Spice Corner", Cuisine = "North Indian", City = "Kolkata", Rating = 3.7, IsOpen = false });
        db.Restaurants.Add(new Restaurant { Name = "Tasty Treats", Cuisine = "Cafe", City = "Bengaluru", Rating = 3.4, IsOpen = false });
        db.Restaurants.Add(new Restaurant { Name = "Royal Kitchen", Cuisine = "Mexican", City = "Chennai", Rating = 4.7, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Spice Hub", Cuisine = "Italian", City = "Chennai", Rating = 4.9, IsOpen = true });
        db.Restaurants.Add(new Restaurant { Name = "Coastal House", Cuisine = "South Indian", City = "Ahmedabad", Rating = 3.8, IsOpen = true });
        db.SaveChanges();
        var r = db.Restaurants.First();

        db.MenuItems.Add(new MenuItem { RestaurantId = 1, Name = "Tandoori Noodles", Category = "Main Course", Price = 240.86m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 1, Name = "Mushroom Roll", Category = "Main Course", Price = 153.96m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 1, Name = "Grilled Fry", Category = "Starter", Price = 412.97m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 1, Name = "Chicken Pasta", Category = "Beverage", Price = 544.92m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 1, Name = "Chilli Tikka", Category = "Dessert", Price = 202.06m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 1, Name = "Chilli Fry", Category = "Main Course", Price = 288.65m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 1, Name = "Grilled Burger", Category = "Starter", Price = 273.24m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 1, Name = "Tandoori Burger", Category = "Beverage", Price = 430.05m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 1, Name = "Veg Roll", Category = "Beverage", Price = 443.53m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 1, Name = "Cheese Pizza", Category = "Main Course", Price = 266.03m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 2, Name = "Masala Noodles", Category = "Main Course", Price = 460.67m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 2, Name = "Butter Cake", Category = "Dessert", Price = 179.46m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 2, Name = "Mushroom Noodles", Category = "Starter", Price = 181.30m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 2, Name = "Mushroom Pasta", Category = "Main Course", Price = 590.92m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 2, Name = "Masala Pasta", Category = "Dessert", Price = 197.10m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 2, Name = "Masala Pizza", Category = "Beverage", Price = 330.96m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 2, Name = "Chilli Pasta", Category = "Main Course", Price = 349.24m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 2, Name = "Grilled Tikka", Category = "Main Course", Price = 227.61m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 3, Name = "Mushroom Pasta", Category = "Beverage", Price = 522.00m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 3, Name = "Mushroom Burger", Category = "Starter", Price = 325.95m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 3, Name = "Masala Biryani", Category = "Beverage", Price = 220.20m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 3, Name = "Veg Noodles", Category = "Beverage", Price = 340.37m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 3, Name = "Cheese Pasta", Category = "Main Course", Price = 546.25m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 4, Name = "Chilli Roll", Category = "Starter", Price = 118.07m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 4, Name = "Mushroom Burger", Category = "Main Course", Price = 358.61m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 4, Name = "Cheese Roll", Category = "Main Course", Price = 457.65m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 4, Name = "Paneer Wrap", Category = "Dessert", Price = 304.17m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 4, Name = "Mushroom Burger", Category = "Beverage", Price = 355.90m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 5, Name = "Paneer Noodles", Category = "Dessert", Price = 289.92m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 5, Name = "Paneer Biryani", Category = "Beverage", Price = 556.72m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 5, Name = "Cheese Noodles", Category = "Starter", Price = 211.21m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 5, Name = "Tandoori Pizza", Category = "Beverage", Price = 330.06m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 5, Name = "Veg Biryani", Category = "Main Course", Price = 333.58m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 5, Name = "Mushroom Burger", Category = "Dessert", Price = 432.02m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 5, Name = "Grilled Noodles", Category = "Main Course", Price = 488.92m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 5, Name = "Butter Pizza", Category = "Dessert", Price = 451.10m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 5, Name = "Chilli Burger", Category = "Beverage", Price = 100.35m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 5, Name = "Butter Pizza", Category = "Dessert", Price = 259.16m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 6, Name = "Cheese Biryani", Category = "Dessert", Price = 175.38m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 6, Name = "Chilli Tikka", Category = "Starter", Price = 512.95m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 6, Name = "Veg Fry", Category = "Dessert", Price = 415.58m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 6, Name = "Paneer Pizza", Category = "Starter", Price = 426.98m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 6, Name = "Cheese Biryani", Category = "Main Course", Price = 526.09m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 6, Name = "Grilled Wrap", Category = "Main Course", Price = 203.27m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 6, Name = "Tandoori Burger", Category = "Starter", Price = 433.23m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 6, Name = "Masala Pizza", Category = "Beverage", Price = 445.40m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 6, Name = "Chicken Roll", Category = "Starter", Price = 376.53m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 6, Name = "Chilli Pizza", Category = "Main Course", Price = 335.62m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 6, Name = "Paneer Roll", Category = "Beverage", Price = 551.73m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 7, Name = "Grilled Burger", Category = "Starter", Price = 179.18m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 7, Name = "Grilled Cake", Category = "Beverage", Price = 431.65m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 7, Name = "Butter Pasta", Category = "Beverage", Price = 598.98m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 7, Name = "Veg Wrap", Category = "Starter", Price = 109.28m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 7, Name = "Butter Biryani", Category = "Beverage", Price = 341.34m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 7, Name = "Paneer Pizza", Category = "Beverage", Price = 411.64m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 7, Name = "Chicken Wrap", Category = "Dessert", Price = 336.27m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 7, Name = "Tandoori Pizza", Category = "Dessert", Price = 316.59m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 8, Name = "Tandoori Tikka", Category = "Dessert", Price = 245.44m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 8, Name = "Chilli Wrap", Category = "Dessert", Price = 535.48m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 8, Name = "Mushroom Roll", Category = "Starter", Price = 264.45m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 8, Name = "Masala Burger", Category = "Starter", Price = 491.11m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 8, Name = "Chilli Fry", Category = "Beverage", Price = 371.70m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 8, Name = "Chilli Noodles", Category = "Starter", Price = 102.11m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 8, Name = "Grilled Cake", Category = "Starter", Price = 493.51m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 8, Name = "Cheese Pasta", Category = "Main Course", Price = 412.41m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 8, Name = "Chicken Pizza", Category = "Starter", Price = 432.50m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 9, Name = "Chicken Burger", Category = "Starter", Price = 309.79m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 9, Name = "Paneer Wrap", Category = "Main Course", Price = 492.27m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 9, Name = "Masala Noodles", Category = "Main Course", Price = 309.89m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 9, Name = "Paneer Pasta", Category = "Starter", Price = 347.88m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 9, Name = "Paneer Biryani", Category = "Beverage", Price = 386.66m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 9, Name = "Grilled Biryani", Category = "Starter", Price = 438.98m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 9, Name = "Cheese Burger", Category = "Beverage", Price = 483.94m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 10, Name = "Chicken Roll", Category = "Main Course", Price = 546.89m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 10, Name = "Chilli Tikka", Category = "Starter", Price = 440.88m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 10, Name = "Chicken Pizza", Category = "Starter", Price = 163.48m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 10, Name = "Masala Cake", Category = "Main Course", Price = 324.39m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 10, Name = "Paneer Wrap", Category = "Main Course", Price = 463.86m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 10, Name = "Masala Fry", Category = "Beverage", Price = 329.29m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 11, Name = "Paneer Tikka", Category = "Starter", Price = 106.36m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 11, Name = "Chicken Pasta", Category = "Dessert", Price = 255.25m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 11, Name = "Veg Roll", Category = "Starter", Price = 257.14m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 11, Name = "Grilled Roll", Category = "Main Course", Price = 171.45m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 11, Name = "Butter Burger", Category = "Beverage", Price = 337.48m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 12, Name = "Cheese Wrap", Category = "Dessert", Price = 238.95m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 12, Name = "Cheese Wrap", Category = "Starter", Price = 514.64m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 12, Name = "Masala Cake", Category = "Beverage", Price = 587.19m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 12, Name = "Chilli Pasta", Category = "Beverage", Price = 399.89m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 12, Name = "Grilled Noodles", Category = "Starter", Price = 259.76m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 12, Name = "Chilli Burger", Category = "Starter", Price = 243.26m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 12, Name = "Cheese Burger", Category = "Dessert", Price = 586.69m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 12, Name = "Grilled Wrap", Category = "Starter", Price = 368.99m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 12, Name = "Chilli Pizza", Category = "Main Course", Price = 253.74m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 13, Name = "Grilled Pizza", Category = "Dessert", Price = 392.19m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 13, Name = "Chilli Roll", Category = "Starter", Price = 367.08m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 13, Name = "Chicken Pizza", Category = "Beverage", Price = 388.80m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 13, Name = "Tandoori Wrap", Category = "Beverage", Price = 352.08m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 13, Name = "Mushroom Pizza", Category = "Main Course", Price = 145.09m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 13, Name = "Butter Cake", Category = "Dessert", Price = 300.25m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 13, Name = "Veg Pizza", Category = "Starter", Price = 560.31m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 13, Name = "Butter Biryani", Category = "Dessert", Price = 415.37m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 13, Name = "Veg Wrap", Category = "Starter", Price = 271.46m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 13, Name = "Cheese Tikka", Category = "Starter", Price = 115.79m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 13, Name = "Grilled Cake", Category = "Main Course", Price = 229.80m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 14, Name = "Chicken Roll", Category = "Main Course", Price = 226.00m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 14, Name = "Butter Pizza", Category = "Main Course", Price = 288.10m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 14, Name = "Paneer Tikka", Category = "Dessert", Price = 534.33m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 14, Name = "Grilled Biryani", Category = "Beverage", Price = 560.08m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 14, Name = "Masala Wrap", Category = "Main Course", Price = 419.32m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 14, Name = "Chilli Burger", Category = "Beverage", Price = 523.85m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 14, Name = "Mushroom Pizza", Category = "Main Course", Price = 118.32m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 14, Name = "Butter Tikka", Category = "Starter", Price = 517.61m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 14, Name = "Masala Fry", Category = "Beverage", Price = 126.88m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 14, Name = "Butter Tikka", Category = "Main Course", Price = 437.44m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 14, Name = "Cheese Cake", Category = "Beverage", Price = 477.95m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 15, Name = "Butter Wrap", Category = "Dessert", Price = 294.02m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 15, Name = "Grilled Pasta", Category = "Main Course", Price = 319.69m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 15, Name = "Paneer Roll", Category = "Main Course", Price = 498.42m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 15, Name = "Mushroom Biryani", Category = "Dessert", Price = 543.35m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 15, Name = "Grilled Biryani", Category = "Beverage", Price = 520.12m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 15, Name = "Grilled Wrap", Category = "Dessert", Price = 510.53m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 15, Name = "Chicken Wrap", Category = "Main Course", Price = 264.99m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 15, Name = "Veg Roll", Category = "Main Course", Price = 318.49m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 15, Name = "Masala Pasta", Category = "Beverage", Price = 222.38m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 15, Name = "Masala Cake", Category = "Dessert", Price = 266.25m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 15, Name = "Masala Roll", Category = "Starter", Price = 258.03m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 15, Name = "Chicken Burger", Category = "Starter", Price = 414.50m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 16, Name = "Masala Biryani", Category = "Dessert", Price = 476.43m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 16, Name = "Chilli Noodles", Category = "Main Course", Price = 561.54m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 16, Name = "Chilli Noodles", Category = "Beverage", Price = 547.10m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 16, Name = "Masala Burger", Category = "Starter", Price = 320.05m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 16, Name = "Butter Fry", Category = "Main Course", Price = 320.50m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 16, Name = "Masala Burger", Category = "Dessert", Price = 316.62m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 16, Name = "Mushroom Noodles", Category = "Main Course", Price = 168.04m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 16, Name = "Tandoori Pizza", Category = "Main Course", Price = 197.36m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 16, Name = "Chicken Cake", Category = "Beverage", Price = 479.64m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 16, Name = "Mushroom Burger", Category = "Main Course", Price = 390.47m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 16, Name = "Paneer Biryani", Category = "Beverage", Price = 519.53m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 16, Name = "Tandoori Wrap", Category = "Dessert", Price = 239.88m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 17, Name = "Paneer Pasta", Category = "Beverage", Price = 165.64m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 17, Name = "Mushroom Burger", Category = "Dessert", Price = 117.34m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 17, Name = "Cheese Cake", Category = "Starter", Price = 277.08m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 17, Name = "Tandoori Biryani", Category = "Starter", Price = 277.36m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 17, Name = "Butter Pasta", Category = "Starter", Price = 244.77m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 17, Name = "Grilled Roll", Category = "Starter", Price = 364.26m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 18, Name = "Paneer Pizza", Category = "Starter", Price = 210.85m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 18, Name = "Veg Biryani", Category = "Dessert", Price = 224.23m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 18, Name = "Paneer Biryani", Category = "Main Course", Price = 229.71m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 18, Name = "Cheese Roll", Category = "Main Course", Price = 450.32m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 18, Name = "Butter Biryani", Category = "Main Course", Price = 121.59m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 18, Name = "Grilled Roll", Category = "Dessert", Price = 154.02m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 18, Name = "Chilli Burger", Category = "Main Course", Price = 529.55m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 19, Name = "Chilli Burger", Category = "Starter", Price = 567.79m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 19, Name = "Chilli Cake", Category = "Starter", Price = 296.82m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 19, Name = "Butter Wrap", Category = "Beverage", Price = 219.19m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 19, Name = "Chilli Cake", Category = "Dessert", Price = 506.52m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 19, Name = "Paneer Wrap", Category = "Main Course", Price = 577.93m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 19, Name = "Mushroom Pasta", Category = "Starter", Price = 281.22m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 19, Name = "Veg Biryani", Category = "Dessert", Price = 315.52m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 19, Name = "Paneer Pizza", Category = "Main Course", Price = 309.36m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 19, Name = "Grilled Tikka", Category = "Starter", Price = 116.19m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 19, Name = "Masala Cake", Category = "Dessert", Price = 413.12m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 19, Name = "Cheese Biryani", Category = "Dessert", Price = 159.85m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 19, Name = "Chilli Pizza", Category = "Starter", Price = 242.76m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 20, Name = "Veg Biryani", Category = "Starter", Price = 396.14m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 20, Name = "Masala Biryani", Category = "Beverage", Price = 394.12m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 20, Name = "Grilled Biryani", Category = "Main Course", Price = 541.60m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 20, Name = "Cheese Noodles", Category = "Dessert", Price = 220.70m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 20, Name = "Tandoori Noodles", Category = "Beverage", Price = 403.98m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 20, Name = "Mushroom Pasta", Category = "Main Course", Price = 373.29m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 20, Name = "Grilled Fry", Category = "Dessert", Price = 405.40m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 20, Name = "Masala Tikka", Category = "Main Course", Price = 265.83m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 20, Name = "Tandoori Fry", Category = "Beverage", Price = 583.80m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 20, Name = "Paneer Wrap", Category = "Main Course", Price = 529.93m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 21, Name = "Tandoori Wrap", Category = "Beverage", Price = 233.96m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 21, Name = "Masala Tikka", Category = "Starter", Price = 178.28m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 21, Name = "Cheese Wrap", Category = "Beverage", Price = 427.86m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 21, Name = "Chilli Roll", Category = "Dessert", Price = 466.71m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 21, Name = "Tandoori Pizza", Category = "Main Course", Price = 307.38m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 21, Name = "Veg Pizza", Category = "Dessert", Price = 509.60m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 21, Name = "Chicken Roll", Category = "Dessert", Price = 491.47m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 21, Name = "Chilli Biryani", Category = "Starter", Price = 304.21m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 21, Name = "Cheese Biryani", Category = "Beverage", Price = 297.75m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 21, Name = "Veg Pasta", Category = "Dessert", Price = 535.38m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 22, Name = "Chilli Roll", Category = "Beverage", Price = 243.03m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 22, Name = "Masala Wrap", Category = "Beverage", Price = 362.06m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 22, Name = "Chilli Wrap", Category = "Starter", Price = 492.54m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 22, Name = "Chilli Roll", Category = "Dessert", Price = 191.11m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 22, Name = "Veg Pasta", Category = "Beverage", Price = 389.79m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 22, Name = "Butter Wrap", Category = "Main Course", Price = 578.38m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 23, Name = "Paneer Tikka", Category = "Starter", Price = 227.27m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 23, Name = "Masala Fry", Category = "Dessert", Price = 368.25m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 23, Name = "Tandoori Fry", Category = "Beverage", Price = 293.76m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 23, Name = "Paneer Cake", Category = "Dessert", Price = 325.53m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 23, Name = "Chicken Fry", Category = "Main Course", Price = 148.48m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 23, Name = "Tandoori Pasta", Category = "Main Course", Price = 538.92m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 23, Name = "Grilled Pasta", Category = "Beverage", Price = 482.66m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 23, Name = "Butter Fry", Category = "Starter", Price = 184.36m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 23, Name = "Butter Biryani", Category = "Dessert", Price = 355.30m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 23, Name = "Masala Wrap", Category = "Beverage", Price = 414.55m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 23, Name = "Masala Fry", Category = "Main Course", Price = 351.44m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 24, Name = "Veg Tikka", Category = "Starter", Price = 275.59m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 24, Name = "Chilli Tikka", Category = "Starter", Price = 252.37m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 24, Name = "Paneer Noodles", Category = "Beverage", Price = 520.08m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 24, Name = "Paneer Tikka", Category = "Main Course", Price = 186.60m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 24, Name = "Cheese Noodles", Category = "Main Course", Price = 386.23m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 24, Name = "Cheese Biryani", Category = "Main Course", Price = 177.39m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 24, Name = "Chicken Tikka", Category = "Starter", Price = 137.07m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 24, Name = "Grilled Roll", Category = "Beverage", Price = 502.30m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 24, Name = "Paneer Cake", Category = "Dessert", Price = 170.96m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 24, Name = "Butter Noodles", Category = "Main Course", Price = 115.45m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 24, Name = "Cheese Biryani", Category = "Dessert", Price = 194.83m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 25, Name = "Paneer Tikka", Category = "Main Course", Price = 544.27m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 25, Name = "Paneer Roll", Category = "Starter", Price = 409.09m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 25, Name = "Mushroom Tikka", Category = "Main Course", Price = 564.41m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 25, Name = "Butter Tikka", Category = "Beverage", Price = 250.84m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 25, Name = "Masala Roll", Category = "Starter", Price = 220.46m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 25, Name = "Cheese Pizza", Category = "Beverage", Price = 253.58m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 25, Name = "Paneer Pizza", Category = "Starter", Price = 185.73m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 25, Name = "Chilli Burger", Category = "Starter", Price = 584.77m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 25, Name = "Chilli Fry", Category = "Dessert", Price = 156.44m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 25, Name = "Chilli Wrap", Category = "Beverage", Price = 424.64m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 25, Name = "Chilli Wrap", Category = "Main Course", Price = 292.68m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 26, Name = "Butter Pizza", Category = "Beverage", Price = 116.46m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 26, Name = "Butter Burger", Category = "Main Course", Price = 451.94m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 26, Name = "Mushroom Noodles", Category = "Main Course", Price = 376.49m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 26, Name = "Mushroom Burger", Category = "Dessert", Price = 275.46m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 26, Name = "Chilli Cake", Category = "Main Course", Price = 247.63m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 26, Name = "Tandoori Pizza", Category = "Main Course", Price = 528.19m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 26, Name = "Masala Cake", Category = "Beverage", Price = 392.78m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 26, Name = "Tandoori Pizza", Category = "Beverage", Price = 403.10m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 26, Name = "Veg Biryani", Category = "Starter", Price = 370.30m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 27, Name = "Paneer Cake", Category = "Main Course", Price = 254.39m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 27, Name = "Chicken Burger", Category = "Main Course", Price = 259.52m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 27, Name = "Chicken Fry", Category = "Dessert", Price = 501.59m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 27, Name = "Mushroom Biryani", Category = "Dessert", Price = 142.97m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 27, Name = "Veg Pasta", Category = "Dessert", Price = 276.95m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 27, Name = "Veg Noodles", Category = "Main Course", Price = 113.79m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 27, Name = "Chilli Tikka", Category = "Beverage", Price = 223.21m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 27, Name = "Butter Biryani", Category = "Main Course", Price = 244.74m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 27, Name = "Cheese Pizza", Category = "Starter", Price = 301.33m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 27, Name = "Veg Pasta", Category = "Main Course", Price = 477.48m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 27, Name = "Chilli Tikka", Category = "Dessert", Price = 413.73m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 28, Name = "Cheese Roll", Category = "Dessert", Price = 561.85m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 28, Name = "Butter Tikka", Category = "Starter", Price = 516.14m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 28, Name = "Paneer Cake", Category = "Starter", Price = 586.06m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 28, Name = "Paneer Wrap", Category = "Main Course", Price = 487.56m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 28, Name = "Chicken Pasta", Category = "Beverage", Price = 598.05m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 28, Name = "Mushroom Noodles", Category = "Starter", Price = 273.52m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 28, Name = "Grilled Wrap", Category = "Beverage", Price = 353.33m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 28, Name = "Chilli Fry", Category = "Main Course", Price = 343.76m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 29, Name = "Tandoori Noodles", Category = "Main Course", Price = 372.20m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 29, Name = "Tandoori Noodles", Category = "Main Course", Price = 580.80m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 29, Name = "Butter Wrap", Category = "Beverage", Price = 145.27m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 29, Name = "Veg Burger", Category = "Beverage", Price = 434.17m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 29, Name = "Mushroom Tikka", Category = "Beverage", Price = 165.55m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 30, Name = "Veg Burger", Category = "Main Course", Price = 265.79m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 30, Name = "Tandoori Pasta", Category = "Main Course", Price = 437.51m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 30, Name = "Cheese Roll", Category = "Beverage", Price = 514.59m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 30, Name = "Masala Tikka", Category = "Dessert", Price = 342.30m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 30, Name = "Paneer Noodles", Category = "Dessert", Price = 197.56m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 30, Name = "Grilled Biryani", Category = "Main Course", Price = 261.24m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 30, Name = "Cheese Wrap", Category = "Dessert", Price = 183.05m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 30, Name = "Paneer Tikka", Category = "Beverage", Price = 595.06m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 30, Name = "Chicken Wrap", Category = "Dessert", Price = 153.40m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 31, Name = "Grilled Pizza", Category = "Dessert", Price = 103.15m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 31, Name = "Masala Cake", Category = "Dessert", Price = 425.54m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 31, Name = "Veg Tikka", Category = "Starter", Price = 486.22m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 31, Name = "Masala Wrap", Category = "Main Course", Price = 580.01m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 31, Name = "Veg Biryani", Category = "Dessert", Price = 470.16m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 31, Name = "Chilli Burger", Category = "Dessert", Price = 259.08m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 31, Name = "Veg Fry", Category = "Dessert", Price = 517.91m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 31, Name = "Mushroom Tikka", Category = "Starter", Price = 152.62m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 31, Name = "Paneer Pizza", Category = "Beverage", Price = 310.49m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 31, Name = "Masala Cake", Category = "Starter", Price = 169.94m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 31, Name = "Veg Burger", Category = "Beverage", Price = 417.38m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 32, Name = "Paneer Roll", Category = "Beverage", Price = 194.41m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 32, Name = "Paneer Tikka", Category = "Beverage", Price = 170.58m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 32, Name = "Paneer Fry", Category = "Beverage", Price = 544.31m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 32, Name = "Grilled Tikka", Category = "Main Course", Price = 551.00m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 32, Name = "Chilli Noodles", Category = "Starter", Price = 320.58m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 32, Name = "Butter Cake", Category = "Main Course", Price = 333.42m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 33, Name = "Tandoori Roll", Category = "Beverage", Price = 584.65m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 33, Name = "Chilli Cake", Category = "Starter", Price = 504.57m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 33, Name = "Butter Cake", Category = "Dessert", Price = 381.51m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 33, Name = "Butter Roll", Category = "Main Course", Price = 248.66m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 33, Name = "Tandoori Tikka", Category = "Main Course", Price = 210.24m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 33, Name = "Chicken Burger", Category = "Dessert", Price = 376.44m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 33, Name = "Butter Fry", Category = "Main Course", Price = 381.41m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 33, Name = "Masala Biryani", Category = "Main Course", Price = 189.25m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 33, Name = "Tandoori Biryani", Category = "Main Course", Price = 530.09m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 33, Name = "Chicken Pizza", Category = "Dessert", Price = 453.55m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 34, Name = "Mushroom Fry", Category = "Starter", Price = 466.79m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 34, Name = "Cheese Biryani", Category = "Beverage", Price = 438.75m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 34, Name = "Veg Fry", Category = "Starter", Price = 412.30m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 34, Name = "Chicken Roll", Category = "Beverage", Price = 371.15m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 34, Name = "Cheese Roll", Category = "Starter", Price = 167.40m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 34, Name = "Paneer Pasta", Category = "Main Course", Price = 122.61m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 34, Name = "Paneer Cake", Category = "Main Course", Price = 328.85m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 34, Name = "Veg Pasta", Category = "Starter", Price = 409.59m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 34, Name = "Cheese Biryani", Category = "Dessert", Price = 183.00m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 34, Name = "Paneer Noodles", Category = "Starter", Price = 218.65m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 34, Name = "Tandoori Wrap", Category = "Beverage", Price = 120.75m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 34, Name = "Butter Biryani", Category = "Dessert", Price = 373.42m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 35, Name = "Paneer Pizza", Category = "Dessert", Price = 276.18m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 35, Name = "Paneer Cake", Category = "Beverage", Price = 155.79m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 35, Name = "Grilled Biryani", Category = "Starter", Price = 499.35m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 35, Name = "Veg Fry", Category = "Dessert", Price = 535.87m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 35, Name = "Veg Cake", Category = "Dessert", Price = 368.22m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 35, Name = "Grilled Tikka", Category = "Starter", Price = 270.18m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 36, Name = "Tandoori Roll", Category = "Starter", Price = 499.23m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 36, Name = "Chicken Burger", Category = "Beverage", Price = 520.48m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 36, Name = "Grilled Pasta", Category = "Main Course", Price = 535.51m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 36, Name = "Tandoori Biryani", Category = "Dessert", Price = 263.64m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 36, Name = "Masala Burger", Category = "Starter", Price = 204.69m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 36, Name = "Grilled Wrap", Category = "Beverage", Price = 292.94m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 36, Name = "Butter Tikka", Category = "Dessert", Price = 388.58m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 36, Name = "Mushroom Tikka", Category = "Main Course", Price = 328.70m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 36, Name = "Paneer Burger", Category = "Main Course", Price = 235.33m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 36, Name = "Chicken Fry", Category = "Dessert", Price = 277.42m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 36, Name = "Tandoori Cake", Category = "Main Course", Price = 595.09m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 36, Name = "Tandoori Biryani", Category = "Main Course", Price = 486.15m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 37, Name = "Butter Noodles", Category = "Main Course", Price = 535.41m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 37, Name = "Chicken Noodles", Category = "Dessert", Price = 468.77m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 37, Name = "Mushroom Wrap", Category = "Beverage", Price = 266.21m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 37, Name = "Butter Roll", Category = "Dessert", Price = 546.10m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 37, Name = "Butter Burger", Category = "Main Course", Price = 201.68m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 37, Name = "Chilli Roll", Category = "Beverage", Price = 383.36m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 38, Name = "Cheese Biryani", Category = "Main Course", Price = 249.74m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 38, Name = "Masala Cake", Category = "Dessert", Price = 135.75m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 38, Name = "Cheese Biryani", Category = "Main Course", Price = 251.12m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 38, Name = "Grilled Wrap", Category = "Beverage", Price = 459.60m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 38, Name = "Grilled Wrap", Category = "Main Course", Price = 236.94m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 38, Name = "Tandoori Tikka", Category = "Main Course", Price = 412.22m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 38, Name = "Paneer Pizza", Category = "Starter", Price = 298.79m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 39, Name = "Tandoori Biryani", Category = "Main Course", Price = 219.87m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 39, Name = "Veg Cake", Category = "Starter", Price = 138.65m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 39, Name = "Butter Burger", Category = "Starter", Price = 193.09m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 39, Name = "Paneer Wrap", Category = "Starter", Price = 205.11m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 39, Name = "Paneer Roll", Category = "Beverage", Price = 403.89m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 39, Name = "Veg Tikka", Category = "Beverage", Price = 497.13m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 39, Name = "Cheese Wrap", Category = "Beverage", Price = 592.91m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 39, Name = "Masala Roll", Category = "Starter", Price = 111.87m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 39, Name = "Cheese Wrap", Category = "Starter", Price = 306.57m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 40, Name = "Chicken Tikka", Category = "Main Course", Price = 204.24m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 40, Name = "Chicken Wrap", Category = "Dessert", Price = 310.62m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 40, Name = "Cheese Fry", Category = "Main Course", Price = 427.68m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 40, Name = "Cheese Wrap", Category = "Main Course", Price = 469.54m, IsAvailable = true });
        db.MenuItems.Add(new MenuItem { RestaurantId = 40, Name = "Grilled Tikka", Category = "Dessert", Price = 424.82m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 40, Name = "Grilled Fry", Category = "Dessert", Price = 279.68m, IsAvailable = false });
        db.MenuItems.Add(new MenuItem { RestaurantId = 40, Name = "Masala Burger", Category = "Dessert", Price = 103.52m, IsAvailable = true });

        db.SaveChanges();

    }
}

app.Run();
